package mixologist

import (
	"github.com/golang/glog"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	sc "google/api/servicecontrol/v1"
	"net/http"
)

type PrometheusReporter struct {
	ReportQueue chan sc.ReportRequest
	MetricMap   map[string]*prometheus.SummaryVec
}

// This code should be generated by looking at schema
func NewPrometheusReporter() ReportConsumer {
	latency := prometheus.NewSummaryVec(
		prometheus.SummaryOpts{
			Name: "api_producer_total_latencies",
			Help: "serviceruntime.googleapis.com/api/producer/total_latencies",
		},
		[]string{"service"},
	)
	mm := make(map[string]*prometheus.SummaryVec)
	mm["serviceruntime.googleapis.com/api/producer/total_latencies"] = latency
	prometheus.MustRegister(latency)
	return &PrometheusReporter{
		MetricMap: mm,
	}
}

func (p *PrometheusReporter) SetReportQueue(ch chan sc.ReportRequest) {
	p.ReportQueue = ch
}

// This loop will not exit until the channel closes
func (p *PrometheusReporter) consumerLoop() {
	glog.Info("Staring prometheus loop")
	for reportMsg := range p.ReportQueue {
		for _, oprn := range reportMsg.GetOperations() {
			for _, le := range oprn.GetLogEntries() {
				fm := le.GetStructPayload().GetFields()
				fm["request_size"].GetNumberValue()

			}
			for _, metric := range oprn.GetMetricValueSets() {
				if summvec, ok := p.MetricMap[metric.MetricName]; ok {
					val := metric.MetricValues[0].GetDistributionValue().Mean
					glog.Info(val)
					glog.Info(metric.MetricValues[0])
					summvec.WithLabelValues("producer").Observe(val)
				}
			}
		}
	}
}

// Do prometheus specific processing here
func (p *PrometheusReporter) Start() {
	p.consumerLoop()
}

// Start a new listener etc.
// Push type (statsd) consumers will only have a consumer loop
// Prometheus needs an additional listerner so that the prometheus
// framework can fetch data from the /metrics endpoint
// For Consumers that
func (p *PrometheusReporter) GetPathandHandler() (string, http.Handler) {
	return "/metrics", promhttp.Handler()
}

// Stop Processing
func (p *PrometheusReporter) Stop() {

}
