# Copyright (C) Endpoints Server Proxy Authors
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

# BookeStore service + ESP service + mixologist service 
# This way one mixologist and one ESP can service multiple services
#

# Bookstore + ESP .js App
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-esp
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: esp
  - port: 8081
    protocol: TCP
    name: bookstore
  selector:
    app: bookstore-esp
  type: LoadBalancer
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: bookstore-esp
spec:
  replicas: 1
  selector:
    app: bookstore-esp
  template:
    metadata:
      labels:
        app: bookstore-esp
    spec:
      volumes:
      - name: bookstore-service-config
        configMap:
          name: bookstore-service-config
      containers:
      - name: bookstore
        image: ${BOOKSTORE_IMAGE}
        ports:
          - containerPort: 8081
      - name: esp
        image: ${ESP_IMAGE}
        args: [
          "--service_json_path", "/tmp/service-config/bookstore.json",
          "--backend", "localhost:8081",
          "--dns", "${dns}"
        ]
        ports:
          - containerPort: 8080
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /tmp/service-config
          name: bookstore-service-config
          readOnly: true
# mixologist
---
apiVersion: v1
kind: Service
metadata:
  name: mixologist
spec:
  ports:
  - port: 9092
    protocol: TCP
    name: mixologist
  selector:
    app: mixologist
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mixologist
spec:
  replicas: 1
  selector:
    app: mixologist
  template:
    metadata:
      labels:
        app: mixologist
    spec:
      containers:
      - name: mixologist
        image: ${MIXOLOGIST_IMAGE}
        args: [
          "-v=0",
          "-logtostderr=true"
        ]
        ports:
          - containerPort: 9092

# prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  ports:
  - port: 9090
    protocol: TCP
    name: prometheus
  selector:
    app: prometheus
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
      containers:
      - name: prometheus
        image: prom/prometheus
        args: [
          "-config.file=/tmp/prometheus/prometheus.yml"
        ]
        ports:
          - containerPort: 9090
        volumeMounts:
        - mountPath: /tmp/prometheus
          name: prometheus-config
          readOnly: true

# grafana
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
  - port: 3000
    protocol: TCP
    name: grafana
  selector:
    app: grafana
  type: LoadBalancer
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
          - containerPort: 3000

# statsd
---
apiVersion: v1
kind: Service
metadata:
  name: statsd
spec:
  ports:
  - port: 8125
    protocol: UDP
    name: statsd
  - port: 80
    protocol: TCP
    name: graphite
  selector:
    app: statsd
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: statsd
spec:
  replicas: 1
  selector:
    app: statsd
  template:
    metadata:
      labels:
        app: statsd
    spec:
      containers:
      - name: statsd
        image: hopsoft/graphite-statsd
        ports:
          - containerPort: 8125
          - containerPort: 80
